### PR TITLE
Update the version of Lein-Ring from 0.12.4 to 0.12.5.

### PR DESCRIPTION
**Pull request by rcorro-gr**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks. Can you change the commit message to:

    Update the version of Lein-Ring

**Comment by rcorro-gr** [comment]
Updated the commit message




Robert Corro

Business Intelligence Developer

robert.corro@rate.com<mailto:robert.corro@rate.com>

www.rate.com<https://www.guaranteedrate.com/?utm_source=grMktg&utm_medium=email&utm_term=&utm_content=text&utm_campaign=sig>

O: (773) 328-6665

320 W. Ohio St Ste 600W, Chicago, IL 60654


[Guaranteed Rate]<http://www.guaranteedrate.com/?utm_source=grMktg&utm_medium=email&utm_term=&utm_content=text&utm_campaign=sig>




Loan Options<https://loanfinder.guaranteedrate.com/#/?loid=9827> - Mobile App<https://guaranteedrate.com/download-mobile-app> - Facebook<http://www.facebook.com/home.php#/pages/guaranteed-Rate/164671984651> - Twitter<http://www.twitter.com/guaranteedrate> - YouTube<http://www.youtube.com/guaranteedrateinc#p/a> - Gateless<http://www.gateless.com/>






[Equal Housing Lender] | © Guaranteed Rate 2017 | 3940 N. Ravenswood Ave., Chicago, IL. 60613

NMLS ID 2611 / NMLS Consumer Access<http://www.nmlsconsumeraccess.com/EntityDetails.aspx/COMPANY/2611> / Licensing Information<https://www.guaranteedrate.com/licensing/?utm_source=grMktg&utm_medium=email>


Please Note: We care about your security and privacy. Please don't include identifying information like account numbers, birth dates and social security numbers in emails to us. Call us instead for secure email options or send the information by fax or regular US mail.
CONFIDENTIALITY AND SECURITY NOTICE The contents of this message and any attachments may be privileged, confidential and proprietary and also may be covered by the Electronic Communications Privacy Act. If you are not an intended recipient, please inform the sender of the transmission error and delete this message immediately without reading, disseminating, distributing or copying the contents. Guaranteed Rate makes no assurances that this e-mail and any attachments are free of viruses and other harmful code.

**Comment by weavejester** [comment]
I'm not seeing the commit message change; I only see a change to the title of the PR.

**Comment by weavejester** [comment]
I've applied the change manually.

**Pull request closed without merging**
